### ISSUE TITLE
Investigate the rogue XC recombination node

### ISSUE THREAD

**Issue by hyanwong** [jeromekelleher/sc2ts-paper#10]
Left middle, here: 

<img width="1195" alt="Screenshot 2023-03-09 at 12 19 55" src="https://user-images.githubusercontent.com/4699014/224021254-1ce0c91d-057f-4779-a10e-5d34f3f4570a.png">

This is the first of two breakpoints in node 251176 in the long ARG:

<img width="1114" alt="Screenshot 2023-03-09 at 12 18 36" src="https://user-images.githubusercontent.com/4699014/224020963-83fd3feb-cd4c-4e1b-be8e-e91faa049215.png">

**Comment by jeromekelleher** [comment]
I think you have to take the HMM's results here - you'd need two extra mutations to go back to P0. It only makes sense to move about between solutions with equal likelihood under the HMM. Otherwise it's a mess.

**Comment by hyanwong** [comment]
Yeah, I think I was misreading the parent (P0) sequence for the ref. I think it might be useful to put the reference sequence in italics in this viz, to avoid this sort of mistake, sorry.

**Comment by hyanwong** [comment]
So actually this could be a valid 3-parent recombinant? There's no easy way to make this "switch back" to a 2 parent version. It might be worth looking in other databases at the causal sample, `USA/MA-CDC-LC0040918/2021` to see what other people have made of it?

**Comment by jeromekelleher** [comment]
Middle parent is also a recombinant, I wouldn't read too much into it.

**Comment by jeromekelleher** [comment]
That parent is almost certainly artefactual, with a large number of descendants. Also note the hmm match has two parents in reverse direction.
