### ISSUE TITLE
Tweaks for method overview figure

### ISSUE THREAD

**Issue by jeromekelleher** [jeromekelleher/sc2ts-paper#131]
A few small changes would improve the method overview figure I think:

1. Change the direction of the "copying" arrows. Sequences copy older sequences, in the algorithm (let's not get into the semantics of this)
2. Use ISO 8601 in the left col for dates (2020-01)
3. Change "recombinant node" to "recombination node"
4. Change dashed arrows in B to solid (makes them seem like a different "type" of edge)
5. We're missing the recombination node in the local trees
6. Maybe use different colours for the two recombinant parents of 4 instead, which could be mirrored in the two local trees below?
7. Don't number the root of the trees in C, D and E as zero (this is misleading, I think). Maybe just drop the node numbers entirely for C and D, as we don't refer to them and it's probably clear enough?
8. Change caption for C to "Tree inference for daily sample cluster"

Does this sound ok @szhan?

**Comment by jeromekelleher** [comment]
Caption wants a few small tweaks also, but might as well wait until final version of the fig is in place.

**Comment by hyanwong** [comment]
FWIW I agree with all of these, apart from

> 4. Change dashed arrows in B to solid (makes them seem like a different "type" of edge)

This doesn't bother me, but I can see the logic. It is helpful, however, to highlight the edges that differ between the two trees in the bottom part of B. Maybe they could be distinguished by shading of colour (although that might still give the impression of a "different sort" of edge. We could justify it by labelling (in the legend) partial-edges as a different colour?

> 7. Don't number the root of the trees in C, D and E as zero (this is misleading, I think). Maybe just drop the node numbers entirely for C and D, as we don't refer to them and it's probably clear enough?

We would need to change the legend, then? Perhaps we need a different symbol for a just-inserted node? We want to make it obvious in C, D, and E which are the nodes we have just inserted. Removing the 0 means that you can't see that so clearly.

> 1. Change the direction of the "copying" arrows. Sequences copy older sequences, in the algorithm (let's not get into the semantics of this)

I think having arrows pointing up (representing the algorithm) risks getting quite confused with the direction of time. Should we perhaps omit the arrows entirely? Also see my comment below about "copying":

Re: the caption, it currently says:

> Sc2ts reconstructs the genetic relationships among SARS- CoV-2 genomes by copying samples to all possible ancestors collected at earlier time points (curved arrows)

"copying to ancestors" sounds weird to me (and I think would confuse non LS experts). Biologically, we copy sequences *from* ancestors. Could we use "matching" language instead:

> Sc2ts reconstructs the genetic relationships among SARS- CoV-2 genomes by matching samples against all possible ancestors collected at earlier time points (curved arrows)

**Comment by jeromekelleher** [comment]
> This doesn't bother me, but I can see the logic. It is helpful, however, to highlight the edges that differ between the two trees in the bottom part of B. Maybe they could be distinguished by shading of colour (although that might still give the impression of a "different sort" of edge. We could justify it by labelling (in the legend) partial-edges as a different colour?

I agree - this is what I was suggesting in 6 I think

**Comment by jeromekelleher** [comment]
> We would need to change the legend, then? Perhaps we need a different symbol for a just-inserted node? We want to make it obvious in C, D, and E which are the nodes we have just inserted. Removing the 0 means that you can't see that so clearly.

Maybe change the "leaf" nodes to a, b, c, d then or something? I'm worried that people will see these as being the same nodes as we're showing in the "global" ARG above and get confused. Particularly for 0 - I don't want people to think that these trees are always rooted at the reference.

**Comment by jeromekelleher** [comment]
> I think having arrows pointing up (representing the algorithm) risks getting quite confused with the direction of time. Should we perhaps omit the arrows entirely? Also see my comment below about "copying":

We can omit at the arrows.

I think the caption needs substantial revision - I agree we shouldn't use the term "copying" here

**Comment by hyanwong** [comment]
> Maybe change the "leaf" nodes to a, b, c, d then or something? I'm worried that people will see these as being the same nodes as we're showing in the "global" ARG above and get confused. Particularly for 0 - I don't want people to think that these trees are always rooted at the reference.

Yeah, great point. Or if there's enough space for 2 digits, we could use 10, 11, 12, 13, 14, ...?

**Comment by jeromekelleher** [comment]
Sure, I don't mind once it's clear these are different nodes to the global ARG immediately above

**Comment by szhan** [comment]
> 1. Change the direction of the "copying" arrows. Sequences copy older sequences, in the algorithm (let's not get into the semantics of this)

Removed all the arrowheads.

> 2. Use ISO 8601 in the left col for dates (2020-01)

Reformatted.

> 3. Change "recombinant node" to "recombination node"

Done.

> 4. Change dashed arrows in B to solid (makes them seem like a different "type" of edge)

They are solid now.

> 5. We're missing the recombination node in the local trees

Added them.

> 6. Maybe use different colours for the two recombinant parents of 4 instead, which could be mirrored in the two local trees below?

Hmm, I'm associating dashed lines with recombinant ancestry. If we are colouring them, should we colour the entire parental genomes, say some shades of blue and purple?

> 7. Don't number the root of the trees in C, D and E as zero (this is misleading, I think). Maybe just drop the node numbers entirely for C and D, as we don't refer to them and it's probably clear enough?

I have followed Yan's suggestion to increment the sample node numbers. This is so that I don't have to change the legend on the side, which indicates that the symbol for a newly added node. In panel C, the existing node 5 in the global ARG serves as the attachment node for new daily samples numbered 7 to 10. In panel D, new daily samples numbered 11 and 12 are attached to the existing node 2 in the global ARG before mutation collapsing. Also, in panel E, it is now shown that a new daily sample numbered 13 is attached to the existing node 1 in the global ARG before reversion pushing.

> 8. Change caption for C to "Tree inference for daily sample cluster"

Done.

Please see working draft below.
<img width="478" alt="Screen Shot 2023-05-26 at 1 25 31 AM" src="https://github.com/jeromekelleher/sc2ts-paper/assets/5580375/abfd7b8d-43a2-4aa1-88f4-5d868a26c0ec">

**Comment by szhan** [comment]
In the legend in the figure, there is a symbol for the "copying" paths. What should we call them instead?

**Comment by jeromekelleher** [comment]
Looks good, thanks @shan!

On second thoughts, "copying path" is good I think, we need to refer to this in some way. We can clarify in the caption and point people to the LS section.

I do think have arrows pointing up would help here in the reference panel. There's surely no confusion about the direction of time, given the trees right next to it, and the great big arrow pointing down showing the direction of time? Younger samples copy from older samples, that's an essential idea to get across. 

I'm note sure  the numbers in C, D and E help here, I think it'll be more confusing and people will think that these are specific nodes referring to something. We're not actually referring to them anywhere, so they don't need to be labelled.

What if we changed the colour of non-sample nodes to red or blue (or something), and then distinguished new-ly added samples by the heavy outer ring? So in the legend we just have three circles with slightly different colours, and no numbers in the middle?

**Comment by jeromekelleher** [comment]
OK, let's just leave them out then

**Comment by szhan** [comment]
> I'm note sure the numbers in C, D and E help here, I think it'll be more confusing and people will think that these are specific nodes referring to something. We're not actually referring to them anywhere, so they don't need to be labelled.

I was thinking about showing how new samples could be added to the global ARG in panel B in new daily batches. But I suppose that it can be confusing and it adds quite a bit of text in the figure legend to explain it all.

**Comment by jeromekelleher** [comment]
Yeah, I think there's enough in there at the moment. We explain the daily batches thing quite a lot in the text, and that's hopefully fairly clear

**Comment by szhan** [comment]
I'm thinking about whether it is a good idea to mention Wuhan-Hu-1 here. It makes the schematic a bit more concrete, but in principle, the root node could be another sample genome or even a reconstructed ancestral genome (say, built using some existing method using early SARS-CoV-2 genomes).

**Comment by jeromekelleher** [comment]
I like the concreteness, lets keep it.

**Comment by szhan** [comment]
I've taken your suggestion using three types of node symbols. Indicating non-sample nodes using blue (aero, #7CB9E8) works pretty nicely, I think.

Also, I've coloured the parental genomes using red (vermillion, #E34234) and purple (amethyst, #9966CC). I don't think we need the dashed edges showing recombinant ancestry, so I've removed them.

Now, I wonder if it is confusing that the parent nodes are not coloured the same way as their corresponding genomes.

Two minor edits:
1. The string specifying date format along the y-axis is capitalised.
2. The genome of the causal recombinant genome (Sample 4) is coloured by red and purple. The red part matching the left parent ends at the second variable site. This should reflect the traceback path obtained in a forward HMM run. Earlier, I had it the other way around.

<img width="429" alt="Screen Shot 2023-05-26 at 11 56 14 AM" src="https://github.com/jeromekelleher/sc2ts-paper/assets/5580375/55c7be00-48a4-4d1f-8a94-961d6e01e8d5">

**Comment by hyanwong** [comment]
I like the blue for non-sample nodes in C, D, E. It works well for highlighting.

**Comment by szhan** [comment]
> I like the blue for non-sample nodes in C, D, E. It works well for highlighting. But shouldn't the node on the LHS of E be grey?

Oops, good catch.

**Comment by szhan** [comment]
I'm not sure whether the parent genomes should be coloured like they are now.

**Comment by szhan** [comment]
Okay, I've adjusted the copying paths. I've updated the colours according to the matplotlib palette, but I prefer the light grey (#CACACA) over the darker grey in the palette.

<img width="480" alt="Screen Shot 2023-05-26 at 12 54 18 PM" src="https://github.com/jeromekelleher/sc2ts-paper/assets/5580375/d407ba97-0945-40a9-a425-e528da29fdc7">

**Comment by jeromekelleher** [comment]
LGTM! Can you open a PR with the changes to the PDF please? What program are you using for this? If it's not totally massive can you include the source file also please?

**Comment by szhan** [comment]
I use Affinity Designer, which uses a custom format. Probably it is easier to just PR the PDF?

**Comment by szhan** [comment]
> I just noticed: the "local trees" are not trees?? I think you need to remove a different branch from each, right?

Crap, I had it correct before in older versions... I did not remove it when adding a recombination node in the local trees.

**Comment by szhan** [comment]
This version then is good enough for this preprint then?

<img width="480" alt="Screen Shot 2023-05-26 at 12 54 18 PM" src="https://github.com/jeromekelleher/sc2ts-paper/assets/5580375/27dfc58b-d662-47ae-b1a7-cae2bf91643f">

**Comment by szhan** [comment]
Hold on. I want to adjust the copying paths a bit.

**Comment by szhan** [comment]
In panel B, the inner copying paths now mirror the edges in the ARG on
<img width="424" alt="Screen Shot 2023-05-26 at 2 25 18 PM" src="https://github.com/jeromekelleher/sc2ts-paper/assets/5580375/818453be-d078-4cd0-a700-a8543edc6f05">
 the right.

**Comment by jeromekelleher** [comment]
I didn't get around to updating the caption, will keep this open for now.

**Comment by jeromekelleher** [comment]
Closing this, caption updated
