### ISSUE TITLE
Fig S3 caption out of date

### ISSUE THREAD

**Issue by jeromekelleher** [jeromekelleher/sc2ts-paper#136]
Discussing HMM consistency, etc

**Comment by hyanwong** [comment]
Done:

> Figure S3: Divergence between parent lineages for recombination events within and among different
> VoC categories. There are 78 Alpha—Alpha recombination breakpoints corresponding to 75 recom-
> bination nodes (25 breakpoints / 24 nodes with ≥ 5 descendant samples). 148 breakpoints from 142
> nodes are Delta—Delta recombinations (45 breakpoints / 45 nodes with ≥ 5 descendants), and 148
> breakpoints from 142 nodes are Omicron—Omicron (71 breakpoints / 68 nodes with ≥ 5 descendants).
> The equivalent figures for Alpha—Delta are 9 / 8 (3 / 2), for Alpha—Omicron are 2 / 1 (0 / 0), and for
> Delta—Omicron are 20 / 13 (6 / 3). Note that these plots do not include recombination breakpoints
> involving lineages that were not classified into these VoC categories.
