### ISSUE TITLE
Checklist before publishing: scan for FIXMEs

### ISSUE THREAD

**Issue by jeromekelleher** [jeromekelleher/sc2ts-paper#142]

**Comment by hyanwong** [comment]
Also `CITATION` and `CITE`.

**Comment by hyanwong** [comment]
Probably also worth looking through the pdf for closing square braces: we have:

> [things important to public health]
> [being a bit rubbish]
> [Katherine - need some input from you here to say this properly?]

**Comment by jeromekelleher** [comment]
Need to check off a few \sally's now
