### ISSUE TITLE
Add numbers quoted in Pango X lineage intro section to notebook

### ISSUE THREAD

**Issue by jeromekelleher** [jeromekelleher/sc2ts-paper#147]
It's not clear where the numbers quoted in the first part of the Pango X lineages section come from. There also seems to be an error with the GISAID numbers when filtering out singletons.

Can we add this to the Pango Recombinant analysis notebook please?

Also it would be nice to now what the overlap in the sets of X lineages between the two methods are - does GISAID just add two extra ones, or is there more disagreement?

**Comment by hyanwong** [comment]
Yep, I have changes to the recombinant notebook. Good point about the error. Probably a typo. I will PR something.

I'll add a stat about overlap too.
