### ISSUE TITLE
Don't use the term "(un)filtered ARG"

### ISSUE THREAD

**Issue by hyanwong** [jeromekelleher/sc2ts-paper#15]
I wrongly introduced the term "filtered ARG" and "unfiltered ARG" (see #14). But it's not the ARG we are filtering, simply the list of recombination nodes, so we need to remove reference to this terminology. Sorry.

**Comment by jeromekelleher** [comment]
Is this done?

**Comment by hyanwong** [comment]
Can we leave it open just the check before the final paper pass?
