### ISSUE TITLE
Section 2.5 query for Katherine

### ISSUE THREAD

**Issue by jeromekelleher** [jeromekelleher/sc2ts-paper#161]
Need to resolve:

> [Sally: KATHERINE, WHAT DO YOU THINK? These not-full-length subgenomic RNA intermediates may provide a lot of omologous templates for some genes more than other (e.g., fig 3B here)]

**Comment by hyanwong** [comment]
@ktmeaton says:

> If you need these notes for revisions:
> 
> MMR value of $k=3
> 
> "...as previous methods have validated that this parameter value has appropriate sensitivity and specificity to detect the majority of designated SARS-CoV- recombinants."
> 
>> With the "previous method" being our current detection pipeline. Direct link https://github.com/ktmeaton/ncov-recombinant, or the Zenodo DOI https://doi.org/10.5281/zenodo.7692522
> 
> If you need a precise percent, I can look that up for you!
> 
>>>  The rate of recombination may also depend on the relative abundance of different subgenomic RNA intermediates

>> (Jerome) Perhaps the simplest thing for your query to Katherine at this point is to comment out that last line, (.i.e. finish with the sentance the "...availability of templates and influencing the rate of homologous recombination (Kim et al., 2020; Zou et al., 2021)

> This makes intuitive sense to me!
