### ISSUE TITLE
Minor visual improvements for figs 1 & 6

### ISSUE THREAD

**Issue by hyanwong** [jeromekelleher/sc2ts-paper#176]
If we want to have complete consistency between figs 1 and 6 (although each of these is completely optional) we might want to

a) Put the order of legend labels (inserted node, recombination node, sample node, newly added sample node) in the same order (see https://github.com/jeromekelleher/sc2ts-paper/issues/156#issuecomment-1576328362)
b) Use the same colour to label mutations (fig 1 uses black/orange for labels & blue bars for mutations, fig 6 uses dark red for numerical count)
c) as part of the point above, we might want to place blue bars instead of a number of mutations along a branch. I think this would look nicer and be more visually informative, but it's too much work for the preprint.

**Comment by szhan** [comment]
I'll follow the order in Yan's figure, i.e., inserted node, recombination node, sample node, newly added sample node.

**Comment by szhan** [comment]
Please ignore the red squiggly line.

<img width="720" alt="Screen Shot 2023-06-05 at 8 57 04 PM" src="https://github.com/jeromekelleher/sc2ts-paper/assets/5580375/e28542c5-adb4-4376-a399-dccc777d6035">

**Comment by hyanwong** [comment]
Seems good. Should we have BASE in caps (as the letters are caps). I think it would be helpful to say "optional" or "may be labelled" too, so e.g.

Mutation (may be labelled BASEpositionBASE)

Might it be confusing to put the label in orange when only some of the mutation labels are orange? I guess it's OK / clear though?

**Comment by hyanwong** [comment]
I need to change the order (very slightly) in the subgraphs to match this.

**Comment by hyanwong** [comment]
> I'm just going with "Mutation (labelled BASEpositionBASE)". It gets too long otherwise, I think.

SGTM. `(labels: BASEpositionBASE)` is a tiny bit shorter (but perhaps less obvious) if that helps.

**Comment by szhan** [comment]
I made that piece of text a bit smaller than the "Mutation" text. It looks better, I think.

<img width="385" alt="Screen Shot 2023-06-07 at 2 37 07 PM" src="https://github.com/jeromekelleher/sc2ts-paper/assets/5580375/1e5a6e8d-ed8f-4bbe-a8ea-4890cd3a1c5c">
