### ISSUE TITLE
Add forward refs to FP section

### ISSUE THREAD

**Issue by jeromekelleher** [jeromekelleher/sc2ts-paper#181]
- Intro dicussion about X lineages. We're basically now saying that we don't think a bunch of things are recombinants, since they descend from Table 3C. right?
- Backbone phylo section. We want to ref forward here, saying these recombs are likely examples of what we see there

**Comment by jeromekelleher** [comment]
> We focus here on the 749 Nextclade-designated recombinant samples, all but two of which descend from a recombination node in the Long ARG.

**Comment by hyanwong** [comment]
I see Sally suggested deleting the entire para. We need to say *something* about the exclusion, however. How about:

>  79 samples (XN: 53, XZ: 16, XAJ: 6, XE:1, XAD: 1, XAH: 1, XAK: 1) trace back to a most recent recombination node that we suspect to be a false positive (row C in Table~\ref{tab:false_positives}, see Section~\ref{sec:false_positives}). For simplicity we exclude these samples from further analyses in this section.

**Comment by jeromekelleher** [comment]
Something like that. Can we keep "we" as meaning "us and the reader" rather than "we the authors" though. So rather than "we suspect", "are likely" or "may be"

**Comment by hyanwong** [comment]
Done
