### ISSUE TITLE
Change mutation notation?

### ISSUE THREAD

**Issue by hyanwong** [jeromekelleher/sc2ts-paper#183]
It is helpful to highlight both reversions and recurrent mutations in the subgraphs. I'm wondering whether this would be a better notation than what we use at the moment:

`A1111T` = a mutation at position 1111 that is not recurrent
`c2222g` = a recurrent mutation at position 2222
`c3333T` = a reversion mutation at pos 3333 back to the inherited state of `T`

So if a mutation begins with a lowercase letter, it is recurrent, but if it ends with a capital letter, it is additionally a reversion.

I don't know how tedious a change this would be for other people. Maybe it's too late, but it is helpful when looking at these plots to highlight the recurrent as well as the reversions.

**Comment by jeromekelleher** [comment]
I assume you tried out colour, boldface, italics etc as other ways of categorising?

Agree it would be helpful to highlight recurrent as well as reversion. I don't find the present notation that obvious though

**Comment by hyanwong** [comment]
Done in #185
