### ISSUE TITLE
Fill out the README file in this repo

### ISSUE THREAD

**Issue by hyanwong** [jeromekelleher/sc2ts-paper#198]
We should give a link to the Biorxiv paper when we have it, point to the sc2ts main repo, and say that the ARGs are available from us on request. Oh, and point out the `/notebooks` directory for both examples of code and for replicability of figures etc.

**Comment by szhan** [comment]
https://www.biorxiv.org/content/10.1101/2023.06.08.544212v1

**Comment by hyanwong** [comment]
Fixes in #201
