### ISSUE TITLE
Do not include samples with duplicate genbank IDs

### ISSUE THREAD

**Issue by hyanwong** [jeromekelleher/sc2ts-paper#206]
In the current experimental "long" Viridian ARG (viridian-mds_1000_retro_filt-2022-06-30) there are 703 Genbank_revision IDs that correspond to multiple sample nodes. Some of these are diff. runs of the same isolate using diff. protocols (e.g. ERR4969068 and ERR4968970 which both have `"Genbank_accession": "LR963185.3"`. As we are using the Genbank accession number for matching to Nextstrain, we should probably just chuck these away before running sc2ts?

**Comment by szhan** [comment]
Just checked that the Genbank accessions in the deduplicated, trimmed metadata file are unique across the entries.
