### ISSUE TITLE
Manual addition of select VoC samples to seed sample matching

### ISSUE THREAD

**Issue by szhan** [jeromekelleher/sc2ts-paper#231]
Time-travelling samples make ARG building around the emergence of major VoCs difficult, particularly Delta. One strategy to handle this is to unconditionally insert (relatively) high-quality samples to seed sample matching for each major VoC that is challenging to add (Delta, Omicron BA.1, BA.2, BA.4, XBB, and possibly Alpha).

Let's use Delta as an example. According to the ECDC website (https://www.ecdc.europa.eu/en/covid-19/variants-concern), Delta is estimated to emerge in December 2020. Samples having a reported collection date earlier than December 01, 2020 are considered likely time travellers, and so are immediately excluded. To identify the sample with the most parsimonious path to explain, samples having a later collection date (besides December 31, 2020) are matched against trees built up to the day before the earliest collection date among these samples. In the case of Delta, the earliest collection date is January 09, 2021, so trees built up to January 08, 2021 are used. Each of the 1,211 Delta samples collected up till April 30, 2021 (arbitrarily chosen cutoff) are matched against the 2021-01-08 trees, and then for each of the samples, the number of path segments and mutations in the LS copying path are recorded. Finally, the sample selected for seeding the Delta lineage is the sample that has only one path segment (i.e. no switch), the fewest mutations, and the fewest Ns in its consensus sequence. For Delta, it is the sample ERR5942474 (collected in the UK on 2021-04-19; 728 Ns; 21 mutations when matched to `maskdel-v1-mm_4-f_500-mrm_2-mms_5-mrec_2-rw_7-mgs_10-2021-01-08.ts`).

**Comment by jeromekelleher** [comment]
Superseded by recently opened issues for specific cases.
