### ISSUE TITLE
Add converter for Viridian Usher tree to tskit

### ISSUE THREAD

**Issue by jeromekelleher** [jeromekelleher/sc2ts-paper#241]
We need to do some sort of comparison with the Viridian Usher tree for the paper, and the simplest way to do this is to convert to tskit format. It's a pain, but I guess we only need to do it once and we don't need to worry too much about robustness to changes in Usher, etc.

I'm sure there's some code lying around from earlier attempts at this, which I'll dig up and post in follow-up comments

**Comment by szhan** [comment]
Ah, I was going to do this. The global Viridian UShER trees come in two formats: protobuf and jsonl. I was working off the jsonl file.

Just putting the download link for the tree including batch 1 and batch 2 sequences here for convenience.
https://figshare.com/articles/dataset/Global_Viridian_tree/27194547

**Comment by jeromekelleher** [comment]
Ah - lemme have a look at the JSON file.

**Comment by jeromekelleher** [comment]
Ah great, the json format looks really straightforward. Leave it with me, I'll do it now.
