### ISSUE TITLE
Update notebook preprocessing metadata file

### ISSUE THREAD

**Issue by szhan** [jeromekelleher/sc2ts-paper#260]
It'd be good to use the updated metadata file (`run_metadata.v05.tsv`).

This file includes the metadata of the sequences in batch 1 and batch 2 of the Viridian dataset.

There are 5959032 entries, but only 5939984 remain after removing 19048 replicate sequences.

Also, I noticed that there are some updated Pango assignments. The v.05 metadata file has the older Pango assignment as well as the new, provided in these columns:
* Viridian_pangolin
* Viridian_scorpio
* Viridian_pangolin_1.29
* Viridian_scorpio_1.29

**Comment by szhan** [comment]
Note that there are an additional 670080 entries in v0.5 compared to v0.4.

**Comment by jeromekelleher** [comment]
I've been moving to just using the metadata as is, and keeping any processing we need to do within sc2ts. The Args are basically the same, and it's one less thing to document.

What are you actually doing in the preprocessing?

I don't think it's worth deduplicating samples for example, it does no harm having them in there.

**Comment by szhan** [comment]
Hmm, ya, okay. It's just that we deduplicated samples here #257. Agree that it's simpler to not do that.

**Comment by szhan** [comment]
If we don't deduplicate, then the notebook just trims columns that we don't want to keep in the sample metadata.

**Comment by szhan** [comment]
Well, we might as just get rid of this notebook altogether, and import the entire metadata file as is (except for manually renaming the columns `Run` to `strain` and `Date_tree` to `date`).

**Comment by jeromekelleher** [comment]
That's all done in the new Zarr ingest code. Happened while you were away.

**Comment by szhan** [comment]
Alright. No need for this then.
