### ISSUE TITLE
Add code for Mutational spectrum figure

### ISSUE THREAD

**Issue by jeromekelleher** [jeromekelleher/sc2ts-paper#29]
Currently not present

**Comment by jeromekelleher** [comment]
We want to save the data in a CSV in the ``data`` directory, to make it easy to tweak this plot without needing to load up the full dataset or do any calculations.

**Comment by szhan** [comment]
It is a notebook [here](https://github.com/jeromekelleher/sc2ts-paper/blob/main/notebooks/mutational-spectra.ipynb). It downloads the data files from Yi et al.
