### ISSUE TITLE
Finalise graphics for Pango single origin figure

### ISSUE THREAD

**Issue by jeromekelleher** [jeromekelleher/sc2ts-paper#38]
Here's what it looks like as of #36:

![Screenshot from 2023-04-11 16-49-18](https://user-images.githubusercontent.com/2664569/231218360-e54556d7-01b3-49b0-bdb4-8d2609c73d99.png)

I think this works quite well as a narrative, as we can start out with the easy XA example, and then explain how this all fits into a single model which may include shared evolutionary origins, finishing up with an explanation of panel C. It all fits into the section discussing (inferred) single evolutionary origins.

I think we mainly need a colour legend(s?) but can also make things a bit more legible by using more distinguishable colours. I don't think we should try to have a "global" colour scheme here for pango lineages shared across different figures. 

The sizes will vary slightly depending on what information we end up putting in to the table (issue to follow), so we should probably finalise that before fully optimising the layouts.

The XA example will be the first one that people see, so we could add some extra annotations here to tell people what they are looking at .

Any thoughts @hyanwong?

**Comment by hyanwong** [comment]
I do think it would be confusing to have e.g. XA in red in the top plot, then XAG also in red in the bottom plot that you show here. FWIW I used red/orange/magenta for the 3 main recombinant lineages we are focussing on. I do think it helps in the more complex cases (e.g. XB) to have the X-n lineages in orange/red/pink, and other colours for the other lineages (e.g. green for omicron). I'm really not keen on using the Matplotlib default palette, as I don't think it gives enough discrimination, or linking between the related lineages.

We should also make the point that each plot is specifically focussed on XA or XAG - e.g. the XAG plots it doesn't show all the XQs in the wide ARG. Having a strong colour for XAG and weaker pinky ones for the other more "incidental" X lineages in the plot therefore makes some sense to me, but I'm happy to change for something else: I do agree that the XAA/XU/XQ pinky colours are a bit too close. Here's what I have changed it to in #46, but I can have a play to see if I can get the lineages in the XAG plot looking less similar in colour.

[Pango_XA_XAG_XB_nxcld_tight_graph.pdf](https://github.com/jeromekelleher/sc2ts-paper/files/11216372/Pango_XA_XAG_XB_nxcld_tight_graph.pdf)

**Comment by hyanwong** [comment]
Here's an Xn colour scheme where it's a bit easier to distinguish. What do you think?

<img width="921" alt="Screenshot 2023-04-12 at 23 44 29" src="https://user-images.githubusercontent.com/4699014/231602403-64bab901-119a-4568-95bf-b3f0decf8080.png">

**Comment by jeromekelleher** [comment]
That looks very nice, agreed on the points you're making above.

**Comment by hyanwong** [comment]
> That looks very nice, agreed on the points you're making above. 

Thanks.

> I'm just saying that we don't need to have a global colour scheme for Pango lineages across figures (rather than panels).

Yes, I take your point. I've stuck to a global scheme for the Xn plots for simplicity at the moment (as that's how I coded it up), but I think we could very reasonably change to separate schemes for separate plots if we can't see colour differences within each plot when looking with fresh eyes.

Let's keep an eye and revisit when we have all the plots in place, so we know which go together.
