### ISSUE TITLE
Remove parents=2 colouring & in Fig 6 (& suppl)

### ISSUE THREAD

**Issue by jeromekelleher** [jeromekelleher/sc2ts-paper#44]
There doesn't seem to be much information in the num_parents=2 colouring in the mrca divergance figures. I vote we remove it as it's just one more thing to explain (and to confuse people)

**Comment by hyanwong** [comment]
Sure. Happy to remove. I think we should keep the 3-parent ones in there though, so just change all point colours to blue?

It depends if when talking about this, we want to make any 2-parent points?

**Comment by jeromekelleher** [comment]
Yes keep them in just drop the colour distinction
