### ISSUE TITLE
Choose example of multiple-origin Pango recombinant lineage

### ISSUE THREAD

**Issue by hyanwong** [jeromekelleher/sc2ts-paper#55]
We discussed using either XC, XD, XAB (because it is a major component of the XAG plot we are showing), or XS (a deltacron variant)

**Comment by hyanwong** [comment]
Here's XC (63 nodes):

![image](https://user-images.githubusercontent.com/4699014/232106781-3c03eca5-882c-417e-88cb-42b359bbbb88.png)

**Comment by hyanwong** [comment]
Here's XD (22 nodes):

![image](https://user-images.githubusercontent.com/4699014/232106874-1cb383fa-5d2f-4e37-8637-c2363e0bb015.png)

**Comment by hyanwong** [comment]
Here's XAB (185 nodes!):

![image](https://user-images.githubusercontent.com/4699014/232107388-addbb089-3811-41a1-8abb-a839d30ac8b6.png)

**Comment by hyanwong** [comment]
And finally XS (55 nodes):

![image](https://user-images.githubusercontent.com/4699014/232107697-431050e2-d9ec-4541-b94b-133d13ff5f1e.png)

**Comment by hyanwong** [comment]
Seems like XD is the easiest to describe?

**Comment by jeromekelleher** [comment]
What do we get when we  exclude single sample recombination nodes? (See latest version of manuscript)

**Comment by hyanwong** [comment]
> What do we get when we exclude single sample recombination nodes?

WeIl, you can see what would happen e.g. in the XD plot. But I think it would be a bit hard to do in principle because then we remove bits of the topology. In the XD plot it would remove the recombination node to the left of the right-hand XD cluster of 2 nodes, but then would we attach sample tsk584939 directly to the recombination node above the XD nodes? Or just pretend it wasn't there?

**Comment by hyanwong** [comment]
> I guess we could produce a new ARG with all the samples directly below a recombination node removed (and the recombination node removed too)

Here's some code to do that. If we use this, we should do the same for all the node graphs, I guess.
```
is_leaf = np.ones(ts.num_nodes, dtype=bool)
is_leaf[ts.edges_parent] = False
leaves = np.flatnonzero(is_leaf)
edge_to_leaf = np.isin(ts.edges_child, leaves)
# Leaves should only have one edge
assert np.sum(edge_to_leaf) == len(leaves)
edge_below_recomb = np.isin(ts.edges_parent, np.flatnonzero(ts.nodes_flags & sc2ts.NODE_IS_RECOMBINANT))
is_target_edge = np.logical_and(edge_below_recomb, edge_to_leaf)
bad_samples = np.unique(ts.edges_child[is_target_edge])
keep = np.setdiff1d(ts.samples(), bad_samples)
# GISAID EPI ids in metadata refer to node numbers, so we need to keep the same
# numbering using filter_nodes=False
ts = ts.simplify(keep, keep_unary=True, filter_nodes=False)
```

![image](https://user-images.githubusercontent.com/4699014/232414666-5869883d-f85d-4639-9891-079c23b7326b.png)

**Comment by jeromekelleher** [comment]
That looks like an interesting example - shows three parents in both cases, and we're not distracted by possible errors etc by the singletons?
