### ISSUE TITLE
Removing singleton samples below re nodes

### ISSUE THREAD

**Issue by hyanwong** [jeromekelleher/sc2ts-paper#57]
In table 1 we quote "singleton" recombination events, by which I assume we mean 

> no descendant samples (besides the recombinant sequence that triggered insertion of the recombination node)

(rather than e..g. recombination events with more than one breakpoint).

I wonder if it would be more helpful to quote the number of "nonsingleton" events, as those are the ones we have more faith are "real" (and biologically relevant). We could call these e.g. "productive" events, or "founding" events?

Additionally, I tried to remove these samples (and recombination nodes) from the long ARG using the code in https://github.com/jeromekelleher/sc2ts-paper/issues/55#issuecomment-1510840974, but I get different numbers to those quoted in Table1:

```python
ts = tszip.decompress(f"../data/upgma-mds-1000-md-30-mm-3-2022-06-30-recinfo-gisaid-il.ts.tsz")  # long ARG
print(np.sum(ts.nodes_flags & sc2ts.NODE_IS_RECOMBINANT > 0)) # 2078 as expected
print(np.sum(
    remove_singleton_samples_below_re_nodes(ts).simplify(keep_unary=True).nodes_flags & sc2ts.NODE_IS_RECOMBINANT > 0
)) # should be 2078-1315 = 763, but gives 596
```

**Comment by jeromekelleher** [comment]
If you have the TreeInfo you can cross check by something like
```python
np.sum(ti.nodes_max_descendant_samples[recombinants] > 1)
```

The numbers in Table 1 need to be checked (we should just make a notebook to generate them and keep it).

**Comment by hyanwong** [comment]
Ah, if you are using `nodes_max_descendant_samples` it might differ anyway, because a small minority of nodes have only one descendant sample per tree, but more than one descendant sample in total?

**Comment by hyanwong** [comment]
> Doubt this happens much.

You are right. If we do it the long way, we get the same answer:

```python
re_nodes = np.where(ts.nodes_flags & sc2ts.NODE_IS_RECOMBINANT > 0)[0]
print("Num 'max_desc_samples'==1 rec nodes:", np.sum(treeinfo.nodes_max_descendant_samples[re_nodes] == 1))

desc = {u: set() for u in re_nodes}
# Do it the tedious way, tree-by-tree
for tree in ts.trees():
    for u in re_nodes:
        desc[u].update(tree.samples(u))

print("Num 'singleton' recombination nodes:", len([k for k, v in desc.items() if len(v) == 1]))
```

```
Num 'singleton' recombination nodes: 1315
Num 'max_desc_samples'==1 rec nodes: 1315
```

**Comment by jeromekelleher** [comment]
They are the same for n=1 aren't they? Can't have a max of less than 1 .

**Comment by hyanwong** [comment]
Aha, here's why I'm getting a difference:

![image](https://user-images.githubusercontent.com/4699014/232527319-675b2696-3af6-4019-8efc-95380fafd2ff.png)

If I remove singleton samples below a recombination node, I remove all the leaves in this example, including the middle one, and I therefore remove all the black nodes here. I only want to be removing the 2 on the left and 3 on the right.

**Comment by hyanwong** [comment]
Here's the correct code to make a new tree sequence without those samples (and recombination nodes above them):

```python
def remove_singleton_samples_below_re_nodes(ts):
    is_sample_leaf = np.zeros(ts.num_nodes, dtype=bool)
    is_sample_leaf[ts.samples()] = True
    is_sample_leaf[ts.edges_parent] = False
    # parent IDs of sample leaves
    sample_leaf_parents = ts.edges_parent[np.isin(ts.edges_child, np.flatnonzero(is_sample_leaf))]
    # get repeated parent IDs, one for each edge leading to the parent
    sample_leaf_parents = ts.edges_parent[np.isin(ts.edges_parent, sample_leaf_parents)]
    sample_leaf_parents, counts = np.unique(sample_leaf_parents, return_counts=True)
    single_sample_leaf_parents = sample_leaf_parents[counts == 1]
    # Find the ones that are also recombination nodes
    re_nodes = np.flatnonzero(ts.nodes_flags & sc2ts.NODE_IS_RECOMBINANT)
    single_sample_leaf_re = np.intersect1d(re_nodes, single_sample_leaf_parents)
    bad_samples = ts.edges_child[np.isin(ts.edges_parent, single_sample_leaf_re)]
    # All of these should be samples, because they were defined via single edges above a sample
    assert len(np.setdiff1d(bad_samples, ts.samples())) == 0
    keep = np.setdiff1d(ts.samples(), bad_samples)
    return ts.simplify(keep, keep_unary=True, filter_nodes=False)
```
