### ISSUE TITLE
Finalise mutation spectra figure

### ISSUE THREAD

**Issue by jeromekelleher** [jeromekelleher/sc2ts-paper#67]
We want to
- update the captions to be more informative
- Standardise with other figures on colour scheme (use matplotlib default colour wheel, probably)
- Standardise with other figures on font and fig size

We potentially have another panel to add to this though?

**Comment by jeromekelleher** [comment]
@szhan - did you have an idea for a second panel to add to this figure, comparing with data from another paper?

**Comment by jeromekelleher** [comment]
Related: https://github.com/jeromekelleher/sc2ts/issues/148

**Comment by szhan** [comment]
I want to add VoC-specific mutational spectra alongside the whole-tree spectrum we got now. The MBE paper shows differences among the VoC spectra. I think it could be nice to show that as well. It should strengthen the case that the placement of mutations in our ARGs is overall concordant with that in large trees inferred using published phylogenetic methods.
