### ISSUE TITLE
Categorisation into Alpha, Delta, etc.

### ISSUE THREAD

**Issue by hyanwong** [jeromekelleher/sc2ts-paper#8]
After discussion with @szhan, we thought this might work:

```python
def variant_name(pango):
    """
    Classification from the following site
    https://www.cdc.gov/coronavirus/2019-ncov/variants/variant-classifications.html
    Alpha (B.1.1.7 and Q lineages)
    Beta (B.1.351 and descendent lineages)
    Gamma (P.1 and descendent lineages)
    Delta (B.1.617.2 and AY lineages)
    Epsilon (B.1.427 and B.1.429)
    Eta (B.1.525)
    Iota (B.1.526)
    Kappa (B.1.617.1)
    Mu (B.1.621, B.1.621.1)
    Zeta (P.2)
    Omicron (B.1.1.529, BA.1, BA.1.1, BA.2, BA.3, BA.4 and BA.5 lineages)
    """
    if pango == "B.1.1.7" or pango.startswith("Q"):
        return("alpha")
    if pango.startswith("B.1.351"):
        return "beta"
    if pango.startswith("P.1"):
        return "gamma"
    if pango.startswith("AY") or pango == "B.1.617.2":
        return("delta")
    if pango == "B.1.427" or pango == "B.1.429":
        return "epsilon"
    if pango == "B.1.526":
        return "iota"
    if pango == "B.1.617.1":
        return "kappa"
    if pango == "B.1.526":
        return "iota"
    if pango == "B.1.621" or pango == "B.1.621.1":
        return "mu"
    if pango.startswith("P.2"):
        return "zeta"
    if pango == "B.1.1.529" or pango.startswith("BA."):
        return "omicron"
    return("")
```

In the long ARG, that gives the following proportions of samples:

Counter({'': 140053,
         'alpha': 117559,
         'beta': 2200,
         'zeta': 220,
         'epsilon': 4668,
         'iota': 3875,
         'gamma': 5301,
         'delta': 194251,
         'kappa': 173,
         'mu': 288,
         'omicron': 188651})

**Comment by szhan** [comment]
Maybe `pango.startswith("P.1.")` instead of `pango.startswith("P.1")` to be clear that we are including P.1 and nested levels (although we will probably never going to get P.10, P.11, etc.)? Similarly, `B.1.351.` and `P.2.`.

**Comment by hyanwong** [comment]
Then we would not include "P.1" - Is that right?

**Comment by szhan** [comment]
`pango.startswith("P.1") or pango.startswith("P.1.")'?

**Comment by hyanwong** [comment]
You mean `pango == "P.1" or pango.startswith("P.1.")` I think?

**Comment by hyanwong** [comment]
> You mean `pango == "P.1" or pango.startswith("P.1.")` I think?

done this now

**Comment by jeromekelleher** [comment]
is this resolved, and if so can we close it?

**Comment by hyanwong** [comment]
There are still 140053 unclassified ones (but that's more-or-less expected, I guess)

**Comment by hyanwong** [comment]
Should this perhaps be in the main `sc2ts` repo?

**Comment by jeromekelleher** [comment]
Probably
